"""add handrecord room

Revision ID: 010d8e8a08d7
Revises: 7ff9cb0a8db1
Create Date: 2026-07-01 15:30:29.942804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 列类型(如 AutoString)在自动生成迁移里被引用;须随模板带入,否则升级时 NameError


# revision identifiers, used by Alembic.
revision: str = '010d8e8a08d7'
down_revision: Union[str, Sequence[str], None] = '7ff9cb0a8db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 手改(autogen 不完美,见 db-migrations.md):NOT NULL 列加到已有行的表须带默认值,否则既有 handrecord 行报错。
    # server_default='' → 0052 之前的历史手牌 room 记为 ''(哨兵;那时未记 room);ORM 之后一律显式写 room,不依赖此默认。
    with op.batch_alter_table('handrecord', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('room', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False, server_default='')
        )
        batch_op.create_index(batch_op.f('ix_handrecord_room'), ['room'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handrecord_room'))
        batch_op.drop_column('room')

    # ### end Alembic commands ###
