"""add user auth columns

Revision ID: 49417b108733
Revises: 010d8e8a08d7
Create Date: 2026-07-01 17:08:02.987037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 列类型(如 AutoString)在自动生成迁移里被引用;须随模板带入,否则升级时 NameError


# revision identifiers, used by Alembic.
revision: str = '49417b108733'
down_revision: Union[str, Sequence[str], None] = '010d8e8a08d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 三列均 nullable(直用 autogen,无手改):既有 user 行记 NULL = 未启用登录;name 唯一 → 不能给
    # 常量 server_default 回填(多行会撞唯一约束),故走可空 = 最安全的增量迁移(见 changes/0056 决策 1)。
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True))
        batch_op.add_column(sa.Column('hash_password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
        batch_op.add_column(sa.Column('k_user', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_column('k_user')
        batch_op.drop_column('hash_password')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
