"""add dm_message

Revision ID: 79d1fd60fc7f
Revises: d07cf4b8828c
Create Date: 2026-06-26 18:36:34.532021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 列类型(如 AutoString)在自动生成迁移里被引用;须随模板带入,否则升级时 NameError


# revision identifiers, used by Alembic.
revision: str = '79d1fd60fc7f'
down_revision: Union[str, Sequence[str], None] = 'd07cf4b8828c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('from_uid', sa.Integer(), nullable=False),
    sa.Column('to_uid', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_uid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dmmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dmmessage_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_dmmessage_to_uid'), ['to_uid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dmmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dmmessage_to_uid'))
        batch_op.drop_index(batch_op.f('ix_dmmessage_dedupe_key'))

    op.drop_table('dmmessage')
    # ### end Alembic commands ###
