"""add dm_read_cursor

Revision ID: 7ff9cb0a8db1
Revises: 79d1fd60fc7f
Create Date: 2026-06-26 19:05:11.668518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 列类型(如 AutoString)在自动生成迁移里被引用;须随模板带入,否则升级时 NameError


# revision identifiers, used by Alembic.
revision: str = '7ff9cb0a8db1'
down_revision: Union[str, Sequence[str], None] = '79d1fd60fc7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmreadcursor',
    sa.Column('reader_uid', sa.Integer(), nullable=False),
    sa.Column('peer_uid', sa.Integer(), nullable=False),
    sa.Column('read_through_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['peer_uid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reader_uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('reader_uid', 'peer_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dmreadcursor')
    # ### end Alembic commands ###
