"""0.1.3

Revision ID: a7aa829acb7a
Revises: 545f32b59aaa
Create Date: 2025-10-10 07:38:04.646627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a7aa829acb7a'
down_revision: Union[str, Sequence[str], None] = '545f32b59aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_start_time', sa.DateTime(), nullable=False),
    sa.Column('game_end_time', sa.DateTime(), nullable=False),
    sa.Column('rounds_number', sa.Integer(), nullable=False),
    sa.Column('game_players', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamerecord')
    # ### end Alembic commands ###
