"""0.1.1

Revision ID: bb7fa36d10f9
Revises: e9a7880cbbfd
Create Date: 2025-10-09 12:36:31.857178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb7fa36d10f9'
down_revision: Union[str, Sequence[str], None] = 'e9a7880cbbfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=15),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=15),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
