"""baseline new schema: user handrecord handparticipant

Revision ID: d07cf4b8828c
Revises: 
Create Date: 2026-06-24 11:13:49.147183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 列类型(如 AutoString)在自动生成迁移里被引用;须随模板带入,否则升级时 NameError


# revision identifiers, used by Alembic.
revision: str = 'd07cf4b8828c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('final_pot', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handrecord_dedupe_key'), ['dedupe_key'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_nickname'), ['nickname'], unique=True)

    op.create_table('handparticipant',
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('initial_points', sa.Integer(), nullable=False),
    sa.Column('final_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['handrecord.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('hand_id', 'uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('handparticipant')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nickname'))

    op.drop_table('user')
    with op.batch_alter_table('handrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handrecord_dedupe_key'))

    op.drop_table('handrecord')
    # ### end Alembic commands ###
