from dataclasses import dataclass
from enum import StrEnum


class ErrorCode(StrEnum):
    INTERNAL = "INTERNAL"
    NO_SUCH_ROOM = "NO_SUCH_ROOM"
    ROOM_FULL = "ROOM_FULL"
    ALREADY_IN_ROOM = "ALREADY_IN_ROOM"
    NOT_IN_ROOM = "NOT_IN_ROOM"
    SEAT_TAKEN = "SEAT_TAKEN"
    NOT_YOUR_SEAT = "NOT_YOUR_SEAT"
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
    INSUFFICIENT_POINTS = "INSUFFICIENT_POINTS"
    HAND_IN_PROGRESS = "HAND_IN_PROGRESS"
    NO_HAND = "NO_HAND"
    NOT_YOUR_TURN = "NOT_YOUR_TURN"
    ILLEGAL_ACTION = "ILLEGAL_ACTION"
    NOT_ENOUGH_PLAYERS = "NOT_ENOUGH_PLAYERS"
    NO_VOTE_IN_PROGRESS = "NO_VOTE_IN_PROGRESS"
    NOT_A_VOTER = "NOT_A_VOTER"


@dataclass(frozen=True, slots=True)
class Err:
    code: ErrorCode
    detail: str = ""
